### ISSUE TITLE
Script dev 2 hiba

### ISSUE THREAD

**Issue by pisti094** [conan513/SingleCore#1]
A srcipdev 2 ő egyszerüen nem akar bele menni a pack ba néztem az eredetit és még 3-4 fajra sd2 őt is de egyik se ment bele égyszi a becsomagolt magosscript.dll -t valamilyen uton megtunád osztani ?

1>------ Build started: Project: ScriptDev2, Configuration: Release Win32 ------
1>  Extracting revision
1>  precompiled.cpp
1>E:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\dep\ACE_wrappers\ace/Auto_Ptr.inl(72): warning C4150: deletion of pointer to incomplete type 'VehicleKit'; no destructor called
1>          E:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\src\shared\ObjectHandler.h(34) : see declaration of 'VehicleKit'
1>          E:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\dep\ACE_wrappers\ace/Auto_Ptr.inl(70) : while compiling class template member function 'ACE_Auto_Basic_Ptr<X>::~ACE_Auto_Basic_Ptr(void)'
1>          with
1>          [
1>              X=VehicleKit
1>          ]
1>          E:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\dep\ACE_wrappers\ace/Refcounted_Auto_Ptr.inl(82) : while compiling class template member function 'ACE_Refcounted_Auto_Ptr_Rep<X,ACE_LOCK>::~ACE_Refcounted_Auto_Ptr_Rep(void)'
1>          with
1>          [
1>              X=VehicleKit,
1>              ACE_LOCK=ACE_Null_Mutex
1>          ]
1>          E:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\dep\ACE_wrappers\ace/Refcounted_Auto_Ptr.inl(54) : while compiling class template member function 'ACE_Refcounted_Auto_Ptr_Rep<X,ACE_LOCK> *ACE_Refcounted_Auto_Ptr_Rep<X,ACE_LOCK>::attach(ACE_Refcounted_Auto_Ptr_Rep<X,ACE_LOCK> *&)'
1>          with
1>          [
1>              X=VehicleKit,
1>              ACE_LOCK=ACE_Null_Mutex
1>          ]
1>          E:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\dep\ACE_wrappers\ace/Refcounted_Auto_Ptr.inl(99) : see reference to class template instantiation 'ACE_Refcounted_Auto_Ptr_Rep<X,ACE_LOCK>' being compiled
1>          with
1>          [
1>              X=VehicleKit,
1>              ACE_LOCK=ACE_Null_Mutex
1>          ]
1>          E:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\dep\ACE_wrappers\ace/Refcounted_Auto_Ptr.inl(99) : while compiling class template member function 'ACE_Refcounted_Auto_Ptr<X,ACE_LOCK>::ACE_Refcounted_Auto_Ptr(const ACE_Refcounted_Auto_Ptr<X,ACE_LOCK> &)'
1>          with
1>          [
1>              X=VehicleKit,
1>              ACE_LOCK=ACE_Null_Mutex
1>          ]
1>          e:\mangos-mangosr2-wotlk-ai\mangos-mangosr2-wotlk-ai\src\game\Unit.h(2258) : see reference to class template instantiation 'ACE_Refcounted_Auto_Ptr<X,ACE_LOCK>' being compiled
1>          with
1>          [
1>              X=VehicleKit,
1>              ACE_LOCK=ACE_Null_Mutex
1>          ]
1>C:\Program Files\Microsoft Visual Studio 10.0\VC\include\utility(206): error C3859: virtual memory range for PCH exceeded; please recompile with a command line option of '-Zm110' or greater
1>C:\Program Files\Microsoft Visual Studio 10.0\VC\include\utility(206): fatal error C1076: compiler limit : internal heap limit reached; use /Zm to specify a higher limit
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by conan513** [comment]
külön nem lehet sd2t fordítani csak mangossal együtt és csak a sd2R2-t amit mangosr2 fejlesztői csináltak és csak a mappában találhato bat fájlal de az csak akkor megy ha a teljes visual studio 2010 fel van telepítve

persze ez csak windows-on ilyen komplikált én megértem R2 fejlesztőit miért dobták a win fájlokat
